### ISSUE TITLE
fronted/app 在win系统启动报错

### ISSUE THREAD

**Issue by yankwan** [spring2go/staffjoy#6]
app前端引用了npm-zepto包，该包在linux系统下可以正常使用，win系统下npm install 会报错。

通过以下方法win系统可以本地启动成功。

1. package.json中将npm-zepto替换为zepto-webpack，终端执行 `npm install zepto-webpack`。

2. webpack.config.js添加以下代码：
`var webpack = require('webpack');

    plugins: [
        new webpack.ProvidePlugin({
            $: 'zepto-webpack'
        })
     ]
`
3. 将引用`import $ from 'npm-zepto'` 的文件替换为 `import $ from 'zepto-webpack'`。

参考 [zepto-webpack](https://www.npmjs.com/package/zepto-webpack)

**Comment by jskillnet** [comment]
Good, thanks for your contribution!

**Comment by huqingwei311** [comment]
在第一步中就没有找到：npm-zepto？

**Comment by fanyufan** [comment]
> app前端引用了npm-zepto包，该包在linux系统下可以正常使用，win系统下npm install 会报错。
> 
> 通过以下方法win系统可以本地启动成功。
> 
> 1. package.json中将npm-zepto替换为zepto-webpack，终端执行 `npm install zepto-webpack`。
> 2. webpack.config.js添加以下代码：
>    `var webpack = require('webpack');
>    plugins: [
>    new webpack.ProvidePlugin({
>    $: 'zepto-webpack'
>    })
>    ]
>    `
> 3. 将引用`import $ from 'npm-zepto'` 的文件替换为 `import $ from 'zepto-webpack'`。
> 
> 参考 [zepto-webpack](https://www.npmjs.com/package/zepto-webpack)

Good job!!!

**Comment by fanyufan** [comment]
> app前端引用了npm-zepto包，该包在linux系统下可以正常使用，win系统下npm install 会报错。
> 
> 通过以下方法win系统可以本地启动成功。
> 
> 1. package.json中将npm-zepto替换为zepto-webpack，终端执行 `npm install zepto-webpack`。
> 2. webpack.config.js添加以下代码：
>    `var webpack = require('webpack');
>    plugins: [
>    new webpack.ProvidePlugin({
>    $: 'zepto-webpack'
>    })
>    ]
>    `
> 3. 将引用`import $ from 'npm-zepto'` 的文件替换为 `import $ from 'zepto-webpack'`。
> 
> 参考 [zepto-webpack](https://www.npmjs.com/package/zepto-webpack)
Hi yankwan,

Use your method but still show the following errors.

D:\github\staffjoy\frontend\app\webpack.config.js:76
        new webpack.ProvidePlugin({
                    ^

TypeError: Cannot read properties of undefined (reading 'ProvidePlugin')
    at Object.<anonymous> (D:\github\staffjoy\frontend\app\webpack.config.js:76:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (D:\github\staffjoy\frontend\app\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (D:\github\staffjoy\frontend\app\node_modules\webpack-dev-server\bin\webpack-dev-server.js:68:48)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
