### ISSUE TITLE
myaccount容器编译报错

### ISSUE THREAD

**Issue by cechaodeng** [spring2go/staffjoy#64]
是不是镜像的配置有问题

#14 102.4 npm ERR! code 1
#14 102.4 npm ERR! path /build/myaccount/node_modules/node-sass
#14 102.4 npm ERR! command failed
#14 102.4 npm ERR! command sh -c node scripts/build.js
#14 102.4 npm ERR! Building: /usr/local/bin/node /build/myaccount/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#14 102.4 npm ERR! gyp info it worked if it ends with ok
#14 102.4 npm ERR! gyp verb cli [
#14 102.4 npm ERR! gyp verb cli   '/usr/local/bin/node',
#14 102.4 npm ERR! gyp verb cli   '/build/myaccount/node_modules/node-gyp/bin/node-gyp.js',
#14 102.4 npm ERR! gyp verb cli   'rebuild',
#14 102.4 npm ERR! gyp verb cli   '--verbose',
#14 102.4 npm ERR! gyp verb cli   '--libsass_ext=',
#14 102.4 npm ERR! gyp verb cli   '--libsass_cflags=',
#14 102.4 npm ERR! gyp verb cli   '--libsass_ldflags=',
#14 102.4 npm ERR! gyp verb cli   '--libsass_library='
#14 102.4 npm ERR! gyp verb cli ]
#14 102.4 npm ERR! gyp info using node-gyp@3.8.0
#14 102.4 npm ERR! gyp info using node@17.3.0 | linux | x64
#14 102.4 npm ERR! gyp verb command rebuild []
#14 102.4 npm ERR! gyp verb command clean []
#14 102.4 npm ERR! gyp verb clean removing "build" directory
#14 102.4 npm ERR! gyp verb command configure []
#14 102.4 npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
#14 102.4 npm ERR! gyp verb `which` failed Error: not found: python2
#14 102.4 npm ERR! gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
#14 102.4 npm ERR! gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
#14 102.4 npm ERR! gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
#14 102.4 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#14 102.4 npm ERR! gyp verb `which` failed  python2 Error: not found: python2
#14 102.4 npm ERR! gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
#14 102.4 npm ERR! gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
#14 102.4 npm ERR! gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
#14 102.4 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#14 102.4 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#14 102.4 npm ERR! gyp verb `which` failed }
#14 102.4 npm ERR! gyp verb check python checking for Python executable "python" in the PATH
#14 102.4 npm ERR! gyp verb `which` failed Error: not found: python
#14 102.4 npm ERR! gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
#14 102.4 npm ERR! gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
#14 102.4 npm ERR! gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
#14 102.4 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#14 102.4 npm ERR! gyp verb `which` failed  python Error: not found: python
#14 102.4 npm ERR! gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
#14 102.4 npm ERR! gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
#14 102.4 npm ERR! gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
#14 102.4 npm ERR! gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
#14 102.4 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#14 102.4 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#14 102.4 npm ERR! gyp verb `which` failed }
#14 102.4 npm ERR! gyp ERR! configure error 
#14 102.4 npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#14 102.4 npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/build/myaccount/node_modules/node-gyp/lib/configure.js:484:19)
#14 102.4 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/build/myaccount/node_modules/node-gyp/lib/configure.js:406:16)
#14 102.4 npm ERR! gyp ERR! stack     at F (/build/myaccount/node_modules/which/which.js:68:16)
#14 102.4 npm ERR! gyp ERR! stack     at E (/build/myaccount/node_modules/which/which.js:80:29)
#14 102.4 npm ERR! gyp ERR! stack     at /build/myaccount/node_modules/which/which.js:89:16
#14 102.4 npm ERR! gyp ERR! stack     at /build/myaccount/node_modules/isexe/index.js:42:5
#14 102.4 npm ERR! gyp ERR! stack     at /build/myaccount/node_modules/isexe/mode.js:8:5
#14 102.4 npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
#14 102.4 npm ERR! gyp ERR! System Linux 5.10.76-linuxkit
#14 102.4 npm ERR! gyp ERR! command "/usr/local/bin/node" "/build/myaccount/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#14 102.4 npm ERR! gyp ERR! cwd /build/myaccount/node_modules/node-sass
#14 102.4 npm ERR! gyp ERR! node -v v17.3.0
#14 102.4 npm ERR! gyp ERR! node-gyp -v v3.8.0
#14 102.4 npm ERR! gyp ERR! not ok 
#14 102.4 npm ERR! Build failed with error code: 1

**Comment by U-boat-ai** [comment]
项目中 node-sass 版本为 4.13，node-sass 与 node 版本有个对应关系，node 用 13 可解决此问题。

**Comment by U-boat-ai** [comment]
> 是不是镜像的配置有问题
> 
> #14 102.4 npm ERR! code 1 #14 102.4 npm ERR! path /build/myaccount/node_modules/node-sass #14 102.4 npm ERR! command failed #14 102.4 npm ERR! command sh -c node scripts/build.js #14 102.4 npm ERR! Building: /usr/local/bin/node /build/myaccount/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= #14 102.4 npm ERR! gyp info it worked if it ends with ok #14 102.4 npm ERR! gyp verb cli [ #14 102.4 npm ERR! gyp verb cli '/usr/local/bin/node', #14 102.4 npm ERR! gyp verb cli '/build/myaccount/node_modules/node-gyp/bin/node-gyp.js', #14 102.4 npm ERR! gyp verb cli 'rebuild', #14 102.4 npm ERR! gyp verb cli '--verbose', #14 102.4 npm ERR! gyp verb cli '--libsass_ext=', #14 102.4 npm ERR! gyp verb cli '--libsass_cflags=', #14 102.4 npm ERR! gyp verb cli '--libsass_ldflags=', #14 102.4 npm ERR! gyp verb cli '--libsass_library=' #14 102.4 npm ERR! gyp verb cli ] #14 102.4 npm ERR! gyp info using node-gyp@3.8.0 #14 102.4 npm ERR! gyp info using node@17.3.0 | linux | x64 #14 102.4 npm ERR! gyp verb command rebuild [] #14 102.4 npm ERR! gyp verb command clean [] #14 102.4 npm ERR! gyp verb clean removing "build" directory #14 102.4 npm ERR! gyp verb command configure [] #14 102.4 npm ERR! gyp verb check python checking for Python executable "python2" in the PATH #14 102.4 npm ERR! gyp verb `which` failed Error: not found: python2 #14 102.4 npm ERR! gyp verb `which` failed at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12) #14 102.4 npm ERR! gyp verb `which` failed at F (/build/myaccount/node_modules/which/which.js:68:19) #14 102.4 npm ERR! gyp verb `which` failed at E (/build/myaccount/node_modules/which/which.js:80:29) #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/which/which.js:89:16 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/index.js:42:5 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/mode.js:8:5 #14 102.4 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) #14 102.4 npm ERR! gyp verb `which` failed python2 Error: not found: python2 #14 102.4 npm ERR! gyp verb `which` failed at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12) #14 102.4 npm ERR! gyp verb `which` failed at F (/build/myaccount/node_modules/which/which.js:68:19) #14 102.4 npm ERR! gyp verb `which` failed at E (/build/myaccount/node_modules/which/which.js:80:29) #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/which/which.js:89:16 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/index.js:42:5 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/mode.js:8:5 #14 102.4 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) { #14 102.4 npm ERR! gyp verb `which` failed code: 'ENOENT' #14 102.4 npm ERR! gyp verb `which` failed } #14 102.4 npm ERR! gyp verb check python checking for Python executable "python" in the PATH #14 102.4 npm ERR! gyp verb `which` failed Error: not found: python #14 102.4 npm ERR! gyp verb `which` failed at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12) #14 102.4 npm ERR! gyp verb `which` failed at F (/build/myaccount/node_modules/which/which.js:68:19) #14 102.4 npm ERR! gyp verb `which` failed at E (/build/myaccount/node_modules/which/which.js:80:29) #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/which/which.js:89:16 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/index.js:42:5 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/mode.js:8:5 #14 102.4 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) #14 102.4 npm ERR! gyp verb `which` failed python Error: not found: python #14 102.4 npm ERR! gyp verb `which` failed at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12) #14 102.4 npm ERR! gyp verb `which` failed at F (/build/myaccount/node_modules/which/which.js:68:19) #14 102.4 npm ERR! gyp verb `which` failed at E (/build/myaccount/node_modules/which/which.js:80:29) #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/which/which.js:89:16 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/index.js:42:5 #14 102.4 npm ERR! gyp verb `which` failed at /build/myaccount/node_modules/isexe/mode.js:8:5 #14 102.4 npm ERR! gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) { #14 102.4 npm ERR! gyp verb `which` failed code: 'ENOENT' #14 102.4 npm ERR! gyp verb `which` failed } #14 102.4 npm ERR! gyp ERR! configure error #14 102.4 npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. #14 102.4 npm ERR! gyp ERR! stack at PythonFinder.failNoPython (/build/myaccount/node_modules/node-gyp/lib/configure.js:484:19) #14 102.4 npm ERR! gyp ERR! stack at PythonFinder. (/build/myaccount/node_modules/node-gyp/lib/configure.js:406:16) #14 102.4 npm ERR! gyp ERR! stack at F (/build/myaccount/node_modules/which/which.js:68:16) #14 102.4 npm ERR! gyp ERR! stack at E (/build/myaccount/node_modules/which/which.js:80:29) #14 102.4 npm ERR! gyp ERR! stack at /build/myaccount/node_modules/which/which.js:89:16 #14 102.4 npm ERR! gyp ERR! stack at /build/myaccount/node_modules/isexe/index.js:42:5 #14 102.4 npm ERR! gyp ERR! stack at /build/myaccount/node_modules/isexe/mode.js:8:5 #14 102.4 npm ERR! gyp ERR! stack at FSReqCallback.oncomplete (node:fs:198:21) #14 102.4 npm ERR! gyp ERR! System Linux 5.10.76-linuxkit #14 102.4 npm ERR! gyp ERR! command "/usr/local/bin/node" "/build/myaccount/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" #14 102.4 npm ERR! gyp ERR! cwd /build/myaccount/node_modules/node-sass #14 102.4 npm ERR! gyp ERR! node -v v17.3.0 #14 102.4 npm ERR! gyp ERR! node-gyp -v v3.8.0 #14 102.4 npm ERR! gyp ERR! not ok #14 102.4 npm ERR! Build failed with error code: 1
项目中 node-sass 版本为 4.13，node-sass 与 node 版本有个对应关系，node 用 13 可解决此问题。
