### ISSUE TITLE
docker-compose build时，myaccount-service构建报错

### ISSUE THREAD

**Issue by ringlog** [spring2go/staffjoy#9]
在按照66节课执行过程中，执行docker-compose build时报错（具体见下），node-sass找不到（https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node）

`Building myaccount-service
Step 1/13 : FROM node:alpine as builder
 ---> f20a6d8b6721
Step 2/13 : WORKDIR '/build'
 ---> Using cache
 ---> 3da06437b10c
Step 3/13 : COPY myaccount ./myaccount
 ---> Using cache
 ---> 932d02a7a07b
Step 4/13 : COPY resources ./resources
 ---> Using cache
 ---> c84b3d9abc28
Step 5/13 : COPY third_party ./third_party
 ---> Using cache
 ---> fb73f7209984
Step 6/13 : WORKDIR '/build/myaccount'
 ---> Using cache
 ---> 788b3be97d9b
Step 7/13 : RUN npm install
 ---> Using cache
 ---> ad730b8837a9
Step 8/13 : RUN npm rebuild node-sass
 ---> Running in bffb04285b8d

> node-sass@4.12.0 install /build/myaccount/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall /build/myaccount/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /build/myaccount/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/build/myaccount/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.1.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/build/myaccount/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/build/myaccount/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/build/myaccount/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/build/myaccount/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /build/myaccount/node_modules/which/which.js:89:16
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /build/myaccount/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (/build/myaccount/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/build/myaccount/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/build/myaccount/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /build/myaccount/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/build/myaccount/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/build/myaccount/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/build/myaccount/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/build/myaccount/node_modules/which/which.js:80:29)
gyp ERR! stack     at /build/myaccount/node_modules/which/which.js:89:16
gyp ERR! stack     at /build/myaccount/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /build/myaccount/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/build/myaccount/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /build/myaccount/node_modules/node-sass
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-10T00_15_16_706Z-debug.log
ERROR: Service 'myaccount-service' failed to build: The command '/bin/sh -c npm rebuild node-sass' returned a non-zero code: 1`

**Comment by ringlog** [comment]
> 在按照66节课执行过程中，执行docker-compose build时报错（具体见下），node-sass找不到（[https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node）](https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node%EF%BC%89)
> 
> `Building myaccount-service
> Step 1/13 : FROM node:alpine as builder
> ---> f20a6d8b6721
> Step 2/13 : WORKDIR '/build'
> ---> Using cache
> ---> 3da06437b10c
> Step 3/13 : COPY myaccount ./myaccount
> ---> Using cache
> ---> 932d02a7a07b
> Step 4/13 : COPY resources ./resources
> ---> Using cache
> ---> c84b3d9abc28
> Step 5/13 : COPY third_party ./third_party
> ---> Using cache
> ---> fb73f7209984
> Step 6/13 : WORKDIR '/build/myaccount'
> ---> Using cache
> ---> 788b3be97d9b
> Step 7/13 : RUN npm install
> ---> Using cache
> ---> ad730b8837a9
> Step 8/13 : RUN npm rebuild node-sass
> ---> Running in bffb04285b8d
> 
> > node-sass@4.12.0 install /build/myaccount/node_modules/node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
> try setting a proxy via HTTP_PROXY, e.g.
> 
> ```
>   export HTTP_PROXY=http://example.com:1234
> ```
> 
> or configure npm proxy via
> 
> ```
>   npm config set proxy http://example.com:8080
> ```
> 
> > node-sass@4.12.0 postinstall /build/myaccount/node_modules/node-sass
> > node scripts/build.js
> 
> Building: /usr/local/bin/node /build/myaccount/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok

...

> gyp ERR! not ok
> Build failed with error code: 1
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.12.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-11-10T00_15_16_706Z-debug.log
> ERROR: Service 'myaccount-service' failed to build: The command '/bin/sh -c npm rebuild node-sass' returned a non-zero code: 1`

---
接下午的一些尝试：
本地单独执行“npm rebuild node-sass”命令是成功的（发现node-sass的下载链接是：https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-57_binding.node）

而重新执行’docker-compose build‘ 的时候仍然失败（构建时寻找的node-sass的下载链接还是：https://github.com/sass/node-sass/releases/download/v4.12.0/linux_musl-x64-79_binding.node），可能容器里用的是linux内核，但是这个版本的node-sass找不到

PS:
macos 10.14 
brew install node@10(brew install node@8也换过，同样本地可以，docker-compose build不行)

**Comment by ringlog** [comment]
根据日志，node是13.1版本，package-lock.json里node-sass的版本为4.12，查看官方兼容列表（https://github.com/sass/node-sass/releases），需要升级到4.13。
解决方法：
将 package-lock.json 中的依赖版本，改为 "node-sass": "^4.13.0",重新docker-compose build ,OK!
